backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/hero.json"
        fields:
          - {label: "Main Title", name: "title", widget: "string"}
          - {label: "Sub Title", name: "subtitle", widget: "text"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Button Text", name: "btn_text", widget: "string"}
